### ISSUE TITLE
Possible rendering issue with border-image-repeat in Webkit

### ISSUE THREAD

**Issue by nlenkowski** [Fyrd/caniuse#2366]
It would appear that "border-image-repeat: round" doesn't work as it should on Webkit, eg. Safari / Mobile Safari. It renders the borders more like the "repeat" value. I've attached a screenshot comparing Chrome and Safari on OS X rendering the following:

```
border-image-slice: 18 18 18 18 fill;   
border-image-width: 10px 10px 10px 10px;   
border-image-outset: 0px 0px 0px 0px;   
border-image-repeat: round round;   
 ```

Here's some[ discussion regarding the issue](http://stackoverflow.com/questions/21390896/border-image-rounding-not-rounding-correctly-in-safari) on stackoverflow.

It might be a good idea to add this as a note on the [border-image](http://caniuse.com/#feat=border-image) property.

![border-image-repeat](https://cloud.githubusercontent.com/assets/1290235/13845427/363b2fe6-ec40-11e5-9c3a-be6f6f53e8c4.png)

**Comment by cvrebert** [comment]
The bug appears to have been fixed in Safari 9.1.

**Comment by nlenkowski** [comment]
Hrmm. I just took a look in Safari 9.1 and Mobile Safari on iOS 9.3. The behavior of the round property has indeed been changed, but it is still not correct. Chrome, Firefox and IE11 and Edge all render the borders as intended, Safari still renders them incorrectly. Maybe it just needs some finessing, but it would appear this property still doesn't work as intended on Webkit.

**Chrome, Firefox and IE11 and Edge**

![all-other-browsers](https://cloud.githubusercontent.com/assets/1290235/14065418/93a17eb6-f428-11e5-8da8-1a4aea4d0159.png)

**Safari 9.1**

![safari-9 1](https://cloud.githubusercontent.com/assets/1290235/14065408/33f63f74-f428-11e5-9a32-933411ce11a4.png)

**Mobile Safari on iOS 9.3**

![mobile-safari-ios9 3](https://cloud.githubusercontent.com/assets/1290235/14065411/49f17730-f428-11e5-9d42-e0b1328e9f29.png)

**Comment by cvrebert** [comment]
@nlenkowski Is your postcard example available as a live webpage somewhere?

**Comment by nlenkowski** [comment]
@cvrebert For now its up at http://dev.frenchmarketchicago.com/contact/, when the site goes into production next week it will be at http://frenchmarketchicago.com/contact/.

**Comment by cvrebert** [comment]
Thanks. I made a reduced testcase based on your example and filed a WebKit bug:
https://bugs.webkit.org/show_bug.cgi?id=155955

**Comment by nlenkowski** [comment]
You bet, and thanks much for opening the WebKit bug.

**Comment by Fyrd** [comment]
Added as known issue.

**Comment by skillmatic-co** [comment]
Surprised this is still a Safari bug in 2021.

**Comment by beamercola** [comment]
@skillmatic-co almost 2023
