### ISSUE TITLE
String.prototype.padStart

### ISSUE THREAD

**Issue by C-Bouthoorn** [Fyrd/caniuse#3143]
As per [this MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart), it already has support on multiple browsers. It'd be nice if you could include this function too.

**Comment by jhpratt** [comment]
Done along with `padEnd()` in #3145

**Comment by dotnetCarpenter** [comment]
@jhpratt Seems that it isn't pushed. https://caniuse.com/#search=padStart and https://caniuse.com/#search=padEnd **0 results found.

**Comment by tomByrer** [comment]
Still not there @Fyrd 
In all browsers but IE11, but helpful to know how far back compat goes.

**Comment by PamProg** [comment]
Still not there @Fyrd

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=pad-start-end
